// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using derTransporte.src.shared.context;

#nullable disable

namespace derTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414014936_PersonRolesMigration")]
    partial class PersonRolesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("derTransporte.src.modules.auditLog.Infrastructure.entity.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("TINYINT(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.authSessions.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.bids.Infrastructure.entity.BidEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("EtaToPickup")
                        .HasColumnType("TIME");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StatusBidsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("VehicleId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.chatMessages.Infrastructure.entity.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsRead")
                        .HasColumnType("TINYINT(1)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.chatRoom.Infrastructure.entity.ChatRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.HasIndex("TripId");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("StateRegId")
                        .HasColumnType("char(36)")
                        .HasColumnName("stateRegId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StateRegId");

                    b.ToTable("cityOrMunicipality", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.cityPricingRules.Infrastructure.entity.CityPricingRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BaseCreditPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("TINYINT(1)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("city_pricing_rules", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.companyDocuments.Infrastructure.entity.CompanyDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("company_documents", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.companyVehicles.Infrastructure.entity.CompanyVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("TINYINT(1)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VehicleId");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.creditTransactions.Infrastructure.entity.CreditTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("credit_transactions", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.creditWallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("credit_wallet", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFrequent")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.disputes.Infrastructure.entity.DisputeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReasonCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TripId");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.documentCustomers.Infrastructure.entity.DocumentCustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("documents_customers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.documentDrivers.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("documents_drivers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.documentVehicles.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<short>("ExperienceYears")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.driversVehicles.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("TINYINT(1)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.loadDetails.Infrastructure.entity.LoadDetailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("TINYINT(1)");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("TINYINT(1)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<bool>("RequiredInsurance")
                        .HasColumnType("TINYINT(1)");

                    b.Property<bool>("RequiresPackaging")
                        .HasColumnType("TINYINT(1)");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoadId")
                        .IsUnique();

                    b.ToTable("load_details", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.loadImages.Infrastructure.entity.LoadImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("load_images", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.loadStatusHistory.Infrastructure.entity.LoadStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("LoadId");

                    b.ToTable("load_status_history", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationCoords")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("OfferedPrice")
                        .HasColumnType("DECIMAL");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginCoords")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeLoadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("VolumeM3")
                        .HasColumnType("DECIMAL");

                    b.Property<decimal>("WeightTons")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("loads", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.notifications.Infrastructure.entity.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<sbyte>("IsRead")
                        .HasColumnType("tinyint");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("NotificationTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.payments.Infrastructure.entity.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountMoney")
                        .HasColumnType("DECIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("PaymentProviderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.personPlans.Infrastructure.entity.PersonPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CreditsGranted")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("UnitPriceAtPurchase")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PlanId");

                    b.ToTable("person_plans", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.personRoles.Infrastructure.entity.PersonRolesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.personTransport.Infrastructure.entity.PersonTransportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("TINYINT(1)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RelationTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("person_transport", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<int>("IdentificationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdentificationTypeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<Guid>("PersonStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.plans.Infrastructure.entity.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("DECIMAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.priceHistory.Infrastructure.entity.PriceHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("DATE");

                    b.Property<decimal>("SicetacReferencePrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("TypeLoadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.ratings.Infrastructure.entity.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("EvaluatedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("char(36)");

                    b.Property<short>("Score")
                        .HasColumnType("SMALLINT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("TripId");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.returnLoadSuggestions.Infrastructure.entity.ReturnLoadSugEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CurrentLoadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Score")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<Guid>("SuggestedLoadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLoadId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SuggestedLoadId");

                    b.ToTable("return_load_suggestions", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("StateOrRegions");
                });

            modelBuilder.Entity("derTransporte.src.modules.subscriptions.Infrastructure.entity.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("TINYINT(1)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubscriptionTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PersonId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("EmailCorp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("LegalRepresentativeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("EmailCorp")
                        .IsUnique();

                    b.HasIndex("LegalRepresentativeId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("transport_companies", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.travelScale.Infrastructure.entity.TravelScaleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArrivalActual")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("ArrivalEstimated")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DepartureActual")
                        .HasColumnType("DATETIME");

                    b.Property<short>("Sequence")
                        .HasColumnType("SMALLINT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TripId");

                    b.ToTable("travel_scale", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.tripStatusHistory.Infrastructure.entity.TripStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LocationCoords")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("trip_status_history", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BidId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("DECIMAL");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ManifestNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("TrackingToken")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.auditLog.Infrastructure.entity.AuditLogEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("AuthCredential")
                        .HasForeignKey("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.authSessions.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.bids.Infrastructure.entity.BidEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany("Bids")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithMany("Bids")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Load");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("derTransporte.src.modules.chatMessages.Infrastructure.entity.ChatMessageEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.chatRoom.Infrastructure.entity.ChatRoomEntity", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("derTransporte.src.modules.chatRoom.Infrastructure.entity.ChatRoomEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", "StateOrRegion")
                        .WithMany("CitiesOrMunicipalities")
                        .HasForeignKey("StateRegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateOrRegion");
                });

            modelBuilder.Entity("derTransporte.src.modules.cityPricingRules.Infrastructure.entity.CityPricingRuleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("derTransporte.src.modules.companyDocuments.Infrastructure.entity.CompanyDocumentEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", "Company")
                        .WithMany("Documents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("derTransporte.src.modules.companyVehicles.Infrastructure.entity.CompanyVehicleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", "Company")
                        .WithMany("CompanyVehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany("CompanyVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("derTransporte.src.modules.creditTransactions.Infrastructure.entity.CreditTransactionEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.creditWallet.Infrastructure.entity.CreditWalletEntity", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("derTransporte.src.modules.creditWallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("Customer")
                        .HasForeignKey("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.disputes.Infrastructure.entity.DisputeEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany("Disputes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.documentCustomers.Infrastructure.entity.DocumentCustomerEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("derTransporte.src.modules.documentDrivers.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("derTransporte.src.modules.documentVehicles.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany("Documents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("Driver")
                        .HasForeignKey("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.driversVehicles.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("derTransporte.src.modules.loadDetails.Infrastructure.entity.LoadDetailsEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithOne("LoadDetails")
                        .HasForeignKey("derTransporte.src.modules.loadDetails.Infrastructure.entity.LoadDetailsEntity", "LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("derTransporte.src.modules.loadImages.Infrastructure.entity.LoadImageEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithMany("Images")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("derTransporte.src.modules.loadStatusHistory.Infrastructure.entity.LoadStatusHistoryEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", "Customer")
                        .WithMany("Loads")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_loads_destination_city");

                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_loads_origin_city");

                    b.Navigation("Customer");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("derTransporte.src.modules.notifications.Infrastructure.entity.NotificationEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.payments.Infrastructure.entity.PaymentEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.creditWallet.Infrastructure.entity.CreditWalletEntity", "Wallet")
                        .WithMany("Payments")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("derTransporte.src.modules.personPlans.Infrastructure.entity.PersonPlanEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.payments.Infrastructure.entity.PaymentEntity", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.plans.Infrastructure.entity.PlanEntity", "Plan")
                        .WithMany("PersonPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Person");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("derTransporte.src.modules.personRoles.Infrastructure.entity.PersonRolesEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.personTransport.Infrastructure.entity.PersonTransportEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", "Company")
                        .WithMany("PersonTransports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("derTransporte.src.modules.priceHistory.Infrastructure.entity.PriceHistoryEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_price_history_destination_city");

                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_price_history_origin_city");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("derTransporte.src.modules.ratings.Infrastructure.entity.RatingEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Evaluated")
                        .WithMany()
                        .HasForeignKey("EvaluatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ratings_evaluated");

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ratings_evaluator");

                    b.HasOne("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany("Ratings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluated");

                    b.Navigation("Evaluator");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.returnLoadSuggestions.Infrastructure.entity.ReturnLoadSugEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "CurrentLoad")
                        .WithMany()
                        .HasForeignKey("CurrentLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_return_suggestions_current_load");

                    b.HasOne("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "SuggestedLoad")
                        .WithMany()
                        .HasForeignKey("SuggestedLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_return_suggestions_suggested_load");

                    b.Navigation("CurrentLoad");

                    b.Navigation("Driver");

                    b.Navigation("SuggestedLoad");
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", "Country")
                        .WithMany("statesOrRegions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("derTransporte.src.modules.subscriptions.Infrastructure.entity.SubscriptionEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.payments.Infrastructure.entity.PaymentEntity", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "LegalRepresentative")
                        .WithMany()
                        .HasForeignKey("LegalRepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("LegalRepresentative");
                });

            modelBuilder.Entity("derTransporte.src.modules.travelScale.Infrastructure.entity.TravelScaleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany("TravelScales")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.tripStatusHistory.Infrastructure.entity.TripStatusHistoryEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.bids.Infrastructure.entity.BidEntity", "Bid")
                        .WithOne("Trip")
                        .HasForeignKey("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Driver");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("derTransporte.src.modules.bids.Infrastructure.entity.BidEntity", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("derTransporte.src.modules.chatRoom.Infrastructure.entity.ChatRoomEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", b =>
                {
                    b.Navigation("statesOrRegions");
                });

            modelBuilder.Entity("derTransporte.src.modules.creditWallet.Infrastructure.entity.CreditWalletEntity", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Loads");
                });

            modelBuilder.Entity("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Documents");

                    b.Navigation("DriverVehicles");
                });

            modelBuilder.Entity("derTransporte.src.modules.loads.Infrastructure.entity.LoadEntity", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Images");

                    b.Navigation("LoadDetails");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Navigation("AuthCredential");

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("derTransporte.src.modules.plans.Infrastructure.entity.PlanEntity", b =>
                {
                    b.Navigation("PersonPlans");
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.Navigation("CitiesOrMunicipalities");
                });

            modelBuilder.Entity("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", b =>
                {
                    b.Navigation("CompanyVehicles");

                    b.Navigation("Documents");

                    b.Navigation("PersonTransports");
                });

            modelBuilder.Entity("derTransporte.src.modules.trips.Infrastructure.entity.TripEntity", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Ratings");

                    b.Navigation("StatusHistory");

                    b.Navigation("TravelScales");
                });

            modelBuilder.Entity("derTransporte.src.modules.vehicles.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.Navigation("CompanyVehicles");

                    b.Navigation("Documents");

                    b.Navigation("DriverVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
