// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using derTransporte.src.shared.context;

#nullable disable

namespace derTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413050451_TransportCompaniesMigration")]
    partial class TransportCompaniesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("TINYINT(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("StateRegId")
                        .HasColumnType("char(36)")
                        .HasColumnName("stateRegId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StateRegId");

                    b.ToTable("cityOrMunicipality", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFrequent")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<short>("ExperienceYears")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<int>("IdentificationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdentificationTypeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<Guid>("PersonStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("StateOrRegions");
                });

            modelBuilder.Entity("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("EmailCorp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("LegalRepresentativeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("EmailCorp")
                        .IsUnique();

                    b.HasIndex("LegalRepresentativeId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("transport_companies", (string)null);
                });

            modelBuilder.Entity("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("AuthCredential")
                        .HasForeignKey("derTransporte.src.modules.authCredentials.Infrastructure.entity.AuthCredentialEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", "StateOrRegion")
                        .WithMany("CitiesOrMunicipalities")
                        .HasForeignKey("StateRegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateOrRegion");
                });

            modelBuilder.Entity("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("Customer")
                        .HasForeignKey("derTransporte.src.modules.customers.Infrastructure.entity.CustomerEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "Person")
                        .WithOne("Driver")
                        .HasForeignKey("derTransporte.src.modules.drivers.Infrastructure.entity.DriverEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", "Country")
                        .WithMany("statesOrRegions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("derTransporte.src.modules.transportCompanies.Infrastructure.entity.transportCompanyEntity", b =>
                {
                    b.HasOne("derTransporte.src.modules.cityOrMunicipality.Infrastructure.entity.CityOrMunicipalityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", "LegalRepresentative")
                        .WithMany()
                        .HasForeignKey("LegalRepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("LegalRepresentative");
                });

            modelBuilder.Entity("derTransporte.src.modules.countries.Infrastructure.entity.CountriesEntity", b =>
                {
                    b.Navigation("statesOrRegions");
                });

            modelBuilder.Entity("derTransporte.src.modules.persons.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Navigation("AuthCredential");

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("derTransporte.src.modules.stateOrRegions.Infrastructure.entity.StateOrRegionsEntity", b =>
                {
                    b.Navigation("CitiesOrMunicipalities");
                });
#pragma warning restore 612, 618
        }
    }
}
